[server]
headless = true
address = "0.0.0.0"
port = 5000
enableCORS = false
runOnSave = false
fileWatcherType = "none"
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#4169E1"
backgroundColor = "#F5F7F9"
secondaryBackgroundColor = "#E3E6E8"
textColor = "#262730"
font = "sans serif"
